# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Middle frame
#'
#' Average frame of series of speckle images
#'
#' @param filename A string.
#' @return The array of middle speckle image.
#' @examples
#' library(imager)
#' mf <- middle_frame(filename)
#' plot(as.cimg(mf))
#' @export
middle_frame <- function(filename) {
    .Call('_specklestar_middle_frame', PACKAGE = 'specklestar', filename)
}

ps <- function(filename) {
    .Call('_specklestar_ps', PACKAGE = 'specklestar', filename)
}

#' Speckle Generator
#'
#' Generate model 512 x 512 x 2 (bytes) speckle image of binary star
#'
#' @param seeing A number.
#' @param speckle_sigma A number.
#' @param m1 A number.
#' @param m2 A number.
#' @param rho_x A number.
#' @param rho_y A number.
#' @param wind A number.
#' @section Details:
#' Details here.
#' Details here.
#' @return The vector of model speckle image.
#' @examples
#' # Generate speckle image of binary star with
#' # 7 parameters
#' speckle_vector <- speckle_generator(seeing = 30, speckle_sigma = 1, m1 = 1000, m2 = 900, rho_x = 50, rho_y = 70, wind = 0)
#' speckle_matrix <- matrix(speckle_vector, nrow = 512, ncol = 512)
#'
#' # Plot result
#' library(imager)
#' plot(as.cimg(speckle_matrix))
#' @export
speckle_generator <- function(seeing, speckle_sigma, m1, m2, rho_x, rho_y, wind) {
    .Call('_specklestar_speckle_generator', PACKAGE = 'specklestar', seeing, speckle_sigma, m1, m2, rho_x, rho_y, wind)
}

