# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
timesTwo <- function(x) {
    .Call('_specklestar_timesTwo', PACKAGE = 'specklestar', x)
}

ps <- function(filename) {
    .Call('_specklestar_ps', PACKAGE = 'specklestar', filename)
}

#' @export
speckle_generator <- function(seeing, speckle_sigma, m1, m2, rho_x, rho_y, wind) {
    .Call('_specklestar_speckle_generator', PACKAGE = 'specklestar', seeing, speckle_sigma, m1, m2, rho_x, rho_y, wind)
}

